nullifier = "6364136223846793006"
secret = "13885033948157127959"
path_siblings = [
  "14678909342070756876",   "14340359694176818205",   "3490389784639564826",   "2377159206977889939",   "11136134660641191128",
  "5776246781640716793",   "12360490266823512006",   "7783159857423531983",   "9857737466630432868",   "13004095818351146389",
  "8116512559640647218",   "12170057637489489099",   "18267517067855658160",   "10007402826525227761",   "8371399485941705566",
  "945482789575819655",   "8503743914302291388",   "4681333673231752717",   "8045448350685608778",   "12297150624705552899"
]
path_bits = [
  "0",   "1",   "0",   "1",   "0",
  "1",   "0",   "1",   "0",   "1",
  "0",   "1",   "0",   "1",   "0",
  "1",   "0",   "1",   "0",   "1"
]

# Public values are now outputs of the circuit (root, nullifier_hash).
# They no longer need to be provided here.
nullifier_hash = "1565608087449049416619061943903198865776183104520976486117587040849008336411"
root = "2634098511163448549597990951329529553826382520699944715793596572254420631460"
path_index = "699050"
