[package]
name = "tornado_classic_contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
ultrahonk_soroban_contract = { path = "../.." }
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3cf10a984dba03f68b4f2ed653b715063e983bba", features = ["testutils"] }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "0a0c2df704edeb3cdafabfcc759eddccd6775337" }
num-bigint = "0.4"

[dev-dependencies]

[lib]
name = "tornado_classic_contracts"
path = "lib.rs"
